FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY . /app/

RUN apk add --no-cache git=2.47.2-r0 make=4.4.1-r2 build-base=0.5-r3 && CGO_ENABLED=1 go build .

FROM alpine:3.21 AS runner

RUN adduser -D runner
USER runner
COPY --from=builder --chown=runner /app/backend /app/backend
RUN mkdir /app/database
ENV DATABASE_URL file:/app/database/database.db?mode=rwc
HEALTHCHECK --interval=60s --timeout=15s --start-period=5s --retries=3 CMD wget --no-verbose --tries=1 --spider http://0.0.0.0:8080/health || exit 1

EXPOSE 8080

ENTRYPOINT [ "/app/backend" ]