---
name: Docker Container Build

permissions: read-all

on:
  release:
    types: [published]

jobs:
  build-container:
    name: Build Container And Publish To ghcr.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Release
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker Build Agent
        uses: docker/setup-buildx-action@v3
      - name: Build and Push To ghcr.io
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
