---
name: Quality Checks

# Suggestion from Checkov, probably best to heed it.
permissions: read-all

on:
  # Only lint the main branch when code is pushed
  # or a pull request is made into the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    name: Check Code Quality
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # So CI can report on whether the repository is passing linting
      statuses: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Repository
        uses: super-linter/super-linter/slim@v7.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREATE_LOG_FILE: true
          SAVE_SUPER_LINTER_SUMMARY: true
      - name: Upload Artifacts (If Unsuccessful)
        uses: actions/upload-artifact@v4
        # If any of the prior steps failed (most likely being the linter), upload the logs
        if: ${{ failure() }}
        with:
          name: linting-output-${{ github.run_number }}-${{ github.run_attempt }}
          path: |
            super-linter-output/super-linter-summary.md
            super-linter.log
          # Shouldn't need these artifacts any longer than a day,
          # probably best to save the space on Github's servers
          retention-days: 1
